name: All Tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  tests_goerli_fork:
    name: Run all tests on a Goerli fork
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - name: Build artifacts
        run: yarn build
        env:
          TENDERLY_FORK_URL: ${{ secrets.TENDERLY_FORK_URL }}
      - name: Running tests on a Goerli fork
        run: echo "The GOERLI_URL is:${{ secrets.GOERLI_URL }}"
        run: yarn test:fork
        env:
          GOERLI_URL: ${{ secrets.GOERLI_URL }}
  tests_locally:
    name: Run all tests on a local network
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - name: Build artifacts
        run: yarn build
        env:
          TENDERLY_FORK_URL: ${{ secrets.TENDERLY_FORK_URL }}
      - name: Running tests locally
        run: yarn test:local
