name: Integration Tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test_all:
    name: Run all tests
    runs-on: ubuntu-latest
    env:
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - name: Running tests
        run: yarn test
